<a href="https://colab.research.google.com/github/Kim-Yiji/MID-Project/blob/%ED%99%A9%EB%AF%B8%EC%8A%B9/%EC%A7%80%EC%97%AD%EB%B3%84_%ED%83%9C%EC%96%91%EA%B4%91_%EB%B0%9C%EC%A0%84%EB%9F%89_(19_23)_%EC%B5%9C%EC%A2%85.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')
DATA_PATH = "/content/drive/MyDrive/LikeLion_Data/"

import pandas as pd

Mounted at /content/drive

In [2]:
local19 = pd.read_excel(DATA_PATH + "지역별 태양광 발전량 19.xls")
local19

,구분,1월,2월,3월,4월,5월,6월,7월,8월,9월,10월,11월,12월
0,서울,"2,534.67","2,826.37","3,386.55","4,270.43","4,913.9","4,263.5","3,431.06","4,136.1","3,169.87","3,635.68","3,088.91","2,480.07"
1,부산,"7,874.85","8,388.13","11,017.92","10,448.92","13,096.58","10,978.61","9,401.74","10,601.17","8,465.45","9,239.1","7,956.95","7,624.93"
2,대구,"8,231.26","8,698.82","11,122.05","10,961.28","14,504.64","13,583.24","11,902.42","13,645.24","10,716.87","12,593.16","10,829.6","10,535.06"
3,인천,"4,669.05","5,355.12","6,862.05","7,436.36","9,601.03","8,240.05","6,685.53","8,188.53","5,984.26","6,807.65","5,667.04","4,708.43"
4,광주,"11,572.82","12,448.62","16,943.57","15,681.81","22,282.07","18,488.28","16,122.84","18,449.21","14,843.85","16,601.67","14,354.15","12,064.03"
5,대전,"1,800.65","2,027.43","2,517.93","2,654.12","3,561.32","2,970.34","2,700.41","3,302.05","2,493.57","2,762.91","2,222.28","1,921.67"
6,울산,"3,155.33","3,174.61","4,376.73","4,041.51","5,228.98","4,196.96","3,726.3","4,130.81","3,150.63","3,549.37","3,365.52","3,471.92"
7,세종,"2,723.26","2,899.02","3,705.43","3,873.98","5,008.79","4,443.27","3,740.26","4,217.37","3,241.41","3,888.26","3,271.38","2,748.94"
8,경기,"36,259.17","41,134.18","50,400.17","58,565.38","76,839.6","68,498.03","58,318.08","71,474.08","54,887.83","63,196.18","52,044.87","44,076.91"
9,충북,"33,635.84","37,417.42","45,432.66","49,614.58","68,628.66","61,446.64","50,918.67","60,406.07","46,512.69","53,332.18","45,843.04","39,849.43"
10,충남,"82,667.18","88,364.5","119,112.28","122,334.12","167,828.4","146,716.85","131,712.79","159,964.74","120,214.65","143,384.47","116,221.57","101,795.76"
11,전남,"151,183.88","147,140.93","205,484.09","187,783.48","259,942.17","216,989.52","185,767.33","216,035.23","171,792.41","206,139.89","177,127.81","156,152.77"
12,경북,"82,527.78","87,275.37","109,760.26","110,676.67","143,142.65","126,719.6","107,976.24","123,412.19","97,056.55","112,512.21","97,060.48","96,643.03"
13,경남,"52,200.93","53,764.51","71,739.77","66,005.5","88,401.55","77,375.63","66,476.63","74,097.85","58,832.33","71,607.71","62,740.07","59,326.38"
14,제주,"15,925.27","16,545.24","26,471.47","27,367.7","33,799.88","27,057.83","22,926.63","27,040.55","22,462.72","29,327.43","24,347.64","17,016.38"
15,강원,"56,570.85","62,690.89","71,727.99","82,053.89","105,497.72","91,363.84","74,185.47","86,003","69,935.02","72,787.42","65,091.7","57,111.38"
16,전북,"119,057.57","124,643.25","169,537.73","167,971.45","230,195.9","194,913.56","171,565","199,431.74","159,523.21","186,914.77","157,774.17","141,216.99"

In [3]:
cols = local19.columns[1:13].tolist()
cols

['1월', '2월', '3월', '4월', '5월', '6월', '7월', '8월', '9월', '10월', '11월', '12월']

In [4]:
for col in cols:
  local19[col] = local19[col].str.replace(",", "").astype(float)

In [5]:
local19.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   구분      17 non-null     object
 1   1월      17 non-null     float64
 2   2월      17 non-null     float64
 3   3월      17 non-null     float64
 4   4월      17 non-null     float64
 5   5월      17 non-null     float64
 6   6월      17 non-null     float64
 7   7월      17 non-null     float64
 8   8월      17 non-null     float64
 9   9월      17 non-null     float64
 10  10월     17 non-null     float64
 11  11월     17 non-null     float64
 12  12월     17 non-null     float64
dtypes: float64(12), object(1)
memory usage: 1.9+ KB

In [6]:
local19["총합"] = local19.iloc[:, 1:13].sum(axis=1)
local19

,구분,1월,2월,3월,4월,5월,6월,7월,8월,9월,10월,11월,12월,총합
0,서울,2534.67,2826.37,3386.55,4270.43,4913.90,4263.50,3431.06,4136.10,3169.87,3635.68,3088.91,2480.07,42137.11
1,부산,7874.85,8388.13,11017.92,10448.92,13096.58,10978.61,9401.74,10601.17,8465.45,9239.10,7956.95,7624.93,115094.35
2,대구,8231.26,8698.82,11122.05,10961.28,14504.64,13583.24,11902.42,13645.24,10716.87,12593.16,10829.60,10535.06,137323.64
3,인천,4669.05,5355.12,6862.05,7436.36,9601.03,8240.05,6685.53,8188.53,5984.26,6807.65,5667.04,4708.43,80205.10
4,광주,11572.82,12448.62,16943.57,15681.81,22282.07,18488.28,16122.84,18449.21,14843.85,16601.67,14354.15,12064.03,189852.92
5,대전,1800.65,2027.43,2517.93,2654.12,3561.32,2970.34,2700.41,3302.05,2493.57,2762.91,2222.28,1921.67,30934.68
6,울산,3155.33,3174.61,4376.73,4041.51,5228.98,4196.96,3726.30,4130.81,3150.63,3549.37,3365.52,3471.92,45568.67
7,세종,2723.26,2899.02,3705.43,3873.98,5008.79,4443.27,3740.26,4217.37,3241.41,3888.26,3271.38,2748.94,43761.37
8,경기,36259.17,41134.18,50400.17,58565.38,76839.60,68498.03,58318.08,71474.08,54887.83,63196.18,52044.87,44076.91,675694.48
9,충북,33635.84,37417.42,45432.66,49614.58,68628.66,61446.64,50918.67,60406.07,46512.69,53332.18,45843.04,39849.43,593037.88
10,충남,82667.18,88364.50,119112.28,122334.12,167828.40,146716.85,131712.79,159964.74,120214.65,143384.47,116221.57,101795.76,1500317.31
11,전남,151183.88,147140.93,205484.09,187783.48,259942.17,216989.52,185767.33,216035.23,171792.41,206139.89,177127.81,156152.77,2281539.51
12,경북,82527.78,87275.37,109760.26,110676.67,143142.65,126719.60,107976.24,123412.19,97056.55,112512.21,97060.48,96643.03,1294763.03
13,경남,52200.93,53764.51,71739.77,66005.50,88401.55,77375.63,66476.63,74097.85,58832.33,71607.71,62740.07,59326.38,802568.86
14,제주,15925.27,16545.24,26471.47,27367.70,33799.88,27057.83,22926.63,27040.55,22462.72,29327.43,24347.64,17016.38,290288.74
15,강원,56570.85,62690.89,71727.99,82053.89,105497.72,91363.84,74185.47,86003.00,69935.02,72787.42,65091.70,57111.38,895019.17
16,전북,119057.57,124643.25,169537.73,167971.45,230195.90,194913.56,171565.00,199431.74,159523.21,186914.77,157774.17,141216.99,2022745.34

In [7]:
final19 = pd.pivot_table(local19, index="구분", values="총합")
final19

            총합
구분
강원   895019.17
경기   675694.48
경남   802568.86
경북  1294763.03
광주   189852.92
대구   137323.64
대전    30934.68
부산   115094.35
서울    42137.11
세종    43761.37
울산    45568.67
인천    80205.10
전남  2281539.51
전북  2022745.34
제주   290288.74
충남  1500317.31
충북   593037.88

In [8]:
local20 = pd.read_excel(DATA_PATH + "지역별 태양광 발전량 20.xls")
local20

,구분,1월,2월,3월,4월,5월,6월,7월,8월,9월,10월,11월,12월
0,서울,"2,861.8","3,241.55","4,817.79","5,475.45","4,566","4,762.18","3,727.8","2,967.93","4,259.77","4,418.97","3,075.62","3,524.17"
1,부산,"7,064.22","10,006.01","12,938.59","14,458.51","13,783","13,830.07","8,866.08","12,315.81","10,543.36","12,088.13","9,758.08","10,253.93"
2,대구,"9,420.49","13,163.48","18,256.22","20,798.6","19,879.73","19,057.65","13,165.74","16,679.79","14,503.87","17,917.71","14,275.34","14,696.93"
3,인천,"5,738.15","6,477.92","10,200.25","11,552.61","9,204.02","9,691.72","8,091.62","7,134.51","8,735.34","10,600.81","6,389.69","7,046.36"
4,광주,"11,476.69","15,108.76","23,730.72","27,580.22","23,817.04","21,950.58","15,280.24","19,285.78","17,781.79","20,902.31","14,818.35","13,455.35"
5,대전,"1,935.88","2,549.62","3,742.51","4,341.06","3,965.82","3,656.54","2,603.14","2,957.35","3,104.32","3,230.64","2,340.41","2,264.14"
6,울산,"3,118.17","4,800.26","6,077.77","7,422.82","7,035.7","6,853.78","4,437.75","6,505.63","4,914.71","6,351.65","5,098.37","5,726.34"
7,세종,"2,861.43","3,598.02","5,351.69","6,814.82","6,062.98","5,698.88","4,197.97","4,263.72","5,884.43","5,120.89","3,997.73","3,419.62"
8,경기,"51,912.46","60,680.35","95,588.14","109,507.84","96,252.98","102,305.61","80,254.89","64,510.23","86,640.55","92,308.15","66,707.95","63,130.39"
9,충북,"42,688.83","56,922.82","84,254.51","97,513.98","89,796.02","90,847.48","67,367.37","65,870.49","74,492.8","82,802.54","63,000.68","55,559.16"
10,충남,"108,290.35","143,599.94","219,252.47","254,072.36","216,061.34","211,775.94","166,758.45","171,521.72","196,133.95","211,474.72","150,831.55","144,197.19"
11,전남,"155,970.84","212,446.62","331,148.82","374,136.86","315,445.77","315,242.63","230,521.33","320,595.45","292,073.49","359,122.87","272,805.75","252,254.53"
12,경북,"91,407.15","127,019.43","174,719.33","194,487.96","186,432.54","181,094.86","124,607.41","150,976.3","141,580.2","171,458.15","134,695.05","141,472.26"
13,경남,"56,549.76","78,339.43","102,978.29","115,971.25","105,652.07","102,720.43","67,347.07","91,718.55","84,362.57","110,370.44","85,043.98","84,670.49"
14,제주,"17,171.55","26,152.46","37,222.56","46,547.36","40,184.04","33,822.99","29,185.78","38,024.64","30,309.32","41,527.3","30,279.73","27,936.38"
15,강원,"65,226.25","80,782.37","118,704.51","129,195.14","120,386.6","128,637.54","103,794.64","80,452.04","94,503.37","119,059.25","93,841.05","79,276.8"
16,전북,"132,998.8","189,324.4","282,049.64","323,330.82","284,745.34","268,676.87","202,845.64","252,658.04","253,927.93","285,964.59","209,260.63","196,137.08"

In [9]:
cols = local20.columns[1:13].tolist()
for col in cols:
  local20[col] = local20[col].str.replace(",","").astype(float)

In [10]:
local20["총합"] = local20.iloc[:, 1:13].sum(axis=1)
local20

,구분,1월,2월,3월,4월,5월,6월,7월,8월,9월,10월,11월,12월,총합
0,서울,2861.80,3241.55,4817.79,5475.45,4566.00,4762.18,3727.80,2967.93,4259.77,4418.97,3075.62,3524.17,47699.03
1,부산,7064.22,10006.01,12938.59,14458.51,13783.00,13830.07,8866.08,12315.81,10543.36,12088.13,9758.08,10253.93,135905.79
2,대구,9420.49,13163.48,18256.22,20798.60,19879.73,19057.65,13165.74,16679.79,14503.87,17917.71,14275.34,14696.93,191815.55
3,인천,5738.15,6477.92,10200.25,11552.61,9204.02,9691.72,8091.62,7134.51,8735.34,10600.81,6389.69,7046.36,100863.00
4,광주,11476.69,15108.76,23730.72,27580.22,23817.04,21950.58,15280.24,19285.78,17781.79,20902.31,14818.35,13455.35,225187.83
5,대전,1935.88,2549.62,3742.51,4341.06,3965.82,3656.54,2603.14,2957.35,3104.32,3230.64,2340.41,2264.14,36691.43
6,울산,3118.17,4800.26,6077.77,7422.82,7035.70,6853.78,4437.75,6505.63,4914.71,6351.65,5098.37,5726.34,68342.95
7,세종,2861.43,3598.02,5351.69,6814.82,6062.98,5698.88,4197.97,4263.72,5884.43,5120.89,3997.73,3419.62,57272.18
8,경기,51912.46,60680.35,95588.14,109507.84,96252.98,102305.61,80254.89,64510.23,86640.55,92308.15,66707.95,63130.39,969799.54
9,충북,42688.83,56922.82,84254.51,97513.98,89796.02,90847.48,67367.37,65870.49,74492.80,82802.54,63000.68,55559.16,871116.68
10,충남,108290.35,143599.94,219252.47,254072.36,216061.34,211775.94,166758.45,171521.72,196133.95,211474.72,150831.55,144197.19,2193969.98
11,전남,155970.84,212446.62,331148.82,374136.86,315445.77,315242.63,230521.33,320595.45,292073.49,359122.87,272805.75,252254.53,3431764.96
12,경북,91407.15,127019.43,174719.33,194487.96,186432.54,181094.86,124607.41,150976.30,141580.20,171458.15,134695.05,141472.26,1819950.64
13,경남,56549.76,78339.43,102978.29,115971.25,105652.07,102720.43,67347.07,91718.55,84362.57,110370.44,85043.98,84670.49,1085724.33
14,제주,17171.55,26152.46,37222.56,46547.36,40184.04,33822.99,29185.78,38024.64,30309.32,41527.30,30279.73,27936.38,398364.11
15,강원,65226.25,80782.37,118704.51,129195.14,120386.60,128637.54,103794.64,80452.04,94503.37,119059.25,93841.05,79276.80,1213859.56
16,전북,132998.80,189324.40,282049.64,323330.82,284745.34,268676.87,202845.64,252658.04,253927.93,285964.59,209260.63,196137.08,2881919.78

In [11]:
final20 = pd.pivot_table(local20, index="구분", values="총합")
final20

            총합
구분
강원  1213859.56
경기   969799.54
경남  1085724.33
경북  1819950.64
광주   225187.83
대구   191815.55
대전    36691.43
부산   135905.79
서울    47699.03
세종    57272.18
울산    68342.95
인천   100863.00
전남  3431764.96
전북  2881919.78
제주   398364.11
충남  2193969.98
충북   871116.68

In [12]:
local21 = pd.read_excel(DATA_PATH + "지역별 태양광 발전량 21.xlsx")
local21

/usr/local/lib/python3.10/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

      연도 광역지자체  신재생에너지 합계   재생에너지 합계    신에너지 합계  신재생에너지공급비중        태양광
0   2021    서울    782,277    343,803    438,474        1.54    244,804
1   2021    부산    616,236    322,758    293,478        1.22    268,850
2   2021    대구    251,812    237,111     14,701        0.50    203,414
3   2021    인천  2,020,296    522,823  1,497,473        3.99    222,103
4   2021    광주    345,741    341,185      4,557        0.68    323,404
5   2021    대전    148,871    111,077     37,794        0.29    107,759
6   2021    울산    902,327    846,768     55,559        1.78    147,698
7   2021    세종    170,224    126,389     43,834        0.34     94,225
8   2021    경기  4,733,827  3,280,766  1,453,062        9.34  1,764,822
9   2021    강원  5,888,937  5,740,642    148,294       11.63  1,831,240
10  2021    충북  2,225,401  2,170,437     54,965        4.39  1,407,403
11  2021    충남  8,489,538  5,845,613  2,643,925       16.76  3,094,979
12  2021    전북  8,325,469  8,314,254     11,215       16.43  4,231,407
13  2021    전남  6,158,271  5,928,947    229,324       12.16  5,198,466
14  2021    경북  4,393,519  4,357,360     36,159        8.67  3,076,962
15  2021    경남  2,542,146  2,516,475     25,672        5.02  1,823,756
16  2021    제주  2,662,500  2,662,109        390        5.26    676,330

In [13]:
local21.rename(columns={"태양광":"총합"}, inplace=True)

In [14]:
local21["총합"] = local21["총합"].str.replace(",","").astype(float)

local21.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   연도          17 non-null     int64
 1   광역지자체       17 non-null     object
 2   신재생에너지 합계   17 non-null     object
 3   재생에너지 합계    17 non-null     object
 4   신에너지 합계     17 non-null     object
 5   신재생에너지공급비중  17 non-null     float64
 6   총합          17 non-null     float64
dtypes: float64(2), int64(1), object(4)
memory usage: 1.1+ KB

In [15]:
final21 = pd.pivot_table(local21, index="광역지자체", values="총합")
final21

              총합
광역지자체
강원     1831240.0
경기     1764822.0
경남     1823756.0
경북     3076962.0
광주      323404.0
대구      203414.0
대전      107759.0
부산      268850.0
서울      244804.0
세종       94225.0
울산      147698.0
인천      222103.0
전남     5198466.0
전북     4231407.0
제주      676330.0
충남     3094979.0
충북     1407403.0

In [16]:
local22 = pd.read_excel(DATA_PATH + "지역별 태양광 발전량 22.xlsx")
local22

/usr/local/lib/python3.10/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

      연도 광역지자체   신재생에너지 합계    재생에너지 합계    신에너지 합계  신재생에너지공급비중        태양광
0   2022    서울     723,176     388,180    334,996        1.25    290,528
1   2022    부산     693,590     365,617    327,973        1.20    324,351
2   2022    대구     293,356     278,409     14,947        0.51    253,577
3   2022    인천   1,911,643     564,400  1,347,243        3.31    258,249
4   2022    광주     471,271     406,332     64,940        0.82    390,494
5   2022    대전     224,281     139,650     84,631        0.39    135,265
6   2022    울산     689,744     472,944    216,800        1.19    177,458
7   2022    세종     169,375     128,981     40,394        0.29    112,270
8   2022    경기   5,269,025   3,723,948  1,545,077        9.12  2,133,592
9   2022    강원   6,479,493   6,203,412    276,081       11.21  2,181,578
10  2022    충북   2,785,854   2,579,630    206,224        4.82  1,711,676
11  2022    충남   9,023,827   6,570,279  2,453,548       15.62  3,693,682
12  2022    전북  10,385,213  10,274,015    111,198       17.97  5,534,009
13  2022    전남   7,481,402   7,189,211    292,191       12.95  6,376,158
14  2022    경북   5,315,057   5,285,824     29,233        9.20  4,085,780
15  2022    경남   2,867,620   2,839,026     28,593        4.96  2,279,853
16  2022    제주   2,996,072   2,995,689        383        5.19    787,739

In [17]:
local22.rename(columns={"태양광":"총합"}, inplace=True)

In [18]:
local22["총합"] = local22["총합"].str.replace(",","").astype(float)
local22.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   연도          17 non-null     int64
 1   광역지자체       17 non-null     object
 2   신재생에너지 합계   17 non-null     object
 3   재생에너지 합계    17 non-null     object
 4   신에너지 합계     17 non-null     object
 5   신재생에너지공급비중  17 non-null     float64
 6   총합          17 non-null     float64
dtypes: float64(2), int64(1), object(4)
memory usage: 1.1+ KB

In [19]:
final22 = pd.pivot_table(local22, index="광역지자체", values="총합")
final22

              총합
광역지자체
강원     2181578.0
경기     2133592.0
경남     2279853.0
경북     4085780.0
광주      390494.0
대구      253577.0
대전      135265.0
부산      324351.0
서울      290528.0
세종      112270.0
울산      177458.0
인천      258249.0
전남     6376158.0
전북     5534009.0
제주      787739.0
충남     3693682.0
충북     1711676.0

In [20]:
local23 = pd.read_excel(DATA_PATH + "지역별 태양광 발전량 23.xls")
local23

,구분,1월,2월,3월,4월,5월,6월,7월,8월,9월,10월,11월,12월
0,서울,"3,690.21","4,506.49","5,692.65","5,151.06","6,246.18","5,669.51","4,635.28","4,702.84","4,551.33","4,952.23","3,708.8","2,786.44"
1,부산,"16,552.78","16,014.02","21,194.52","23,182.39","22,866.53","23,670.28","19,069.66","22,588.61","18,078.85","22,562.89","18,428.64","15,680.79"
2,대구,"23,451.51","24,021.02","32,707.26","33,621.53","34,241.43","35,745.38","28,949.92","31,789.4","26,995.55","32,094.46","26,692.69","22,161.5"
3,인천,"8,052.58","9,992.43","12,982.48","11,999","14,293.58","13,720.34","11,525.65","11,947.1","11,153.68","11,921.03","8,541.49","6,809.84"
4,광주,"17,596.51","23,520.9","31,532.22","29,135.16","30,909.39","32,029.03","23,177.62","31,310.26","26,379.55","29,996.53","20,637.14","11,072.52"
5,대전,"3,513.09","3,940.12","5,626.49","5,323.66","5,956.38","6,017.75","4,430.2","5,148.17","4,496.11","5,009.09","3,590.26","2,736.82"
6,울산,"7,486.88","7,163.67","10,157.68","10,618","10,621.83","11,541.2","10,128","10,403.66","8,384.5","11,077.42","9,514.81","7,880.9"
7,세종,"4,724.81","5,795.22","8,065.31","7,332.54","8,818.34","8,632.85","6,392.34","7,375.6","6,362.25","6,977.6","5,175.17","3,398.66"
8,경기,"96,125.05","122,294.1","163,063.01","153,173.97","185,172.38","173,452.59","144,538.02","153,068.94","138,017.89","145,965.18","109,399.6","80,590.8"
9,충북,"92,987.71","109,695.12","152,983.22","145,665.61","166,521.27","166,349.36","128,502.06","143,679.02","126,525.01","134,651.2","104,741.11","70,397.62"
10,충남,"221,947.58","269,002.74","361,349.78","328,672.46","366,971.81","367,768.35","280,378.27","336,207.09","284,707.06","319,150.59","219,583.79","129,863.58"
11,전남,"405,338.23","495,889.88","650,520.7","589,473.59","607,752.62","618,359.26","455,614.82","662,593.07","547,720.3","626,395.17","434,782.9","288,347.21"
12,경북,"249,889.99","260,803.1","357,925.31","360,262.22","381,720.54","394,881.28","312,968.1","337,131.17","295,258.68","345,076.94","277,837.92","229,384.91"
13,경남,"137,044.81","141,396.48","183,099.5","182,988.76","181,122.2","191,906.09","143,608.11","178,204.55","149,106.28","181,723.12","147,677.23","122,097.11"
14,제주,"36,945.81","46,890.2","64,839.46","65,217.46","60,312.35","58,834.26","47,042.76","67,168.06","59,303.45","68,017.06","45,306.34","28,634.9"
15,강원,"102,653.16","148,092.61","204,305.78","191,988.9","226,017.19","215,012.93","179,363.29","176,589.42","164,846.45","175,622.37","138,887.55","96,956.61"
16,전북,"357,180.14","405,649.52","549,019.63","492,354.6","533,021.04","546,738.66","414,973.43","514,665.65","430,489.22","492,891.38","341,233.59","200,732.06"

In [21]:
cols = local23.columns[1:13].tolist()
for col in cols:
  local23[col] = local23[col].str.replace(",","").astype(float)
local23["총합"] = local23.iloc[:, 1:13].sum(axis=1)
local23

,구분,1월,2월,3월,4월,5월,6월,7월,8월,9월,10월,11월,12월,총합
0,서울,3690.21,4506.49,5692.65,5151.06,6246.18,5669.51,4635.28,4702.84,4551.33,4952.23,3708.80,2786.44,56293.02
1,부산,16552.78,16014.02,21194.52,23182.39,22866.53,23670.28,19069.66,22588.61,18078.85,22562.89,18428.64,15680.79,239889.96
2,대구,23451.51,24021.02,32707.26,33621.53,34241.43,35745.38,28949.92,31789.40,26995.55,32094.46,26692.69,22161.50,352471.65
3,인천,8052.58,9992.43,12982.48,11999.00,14293.58,13720.34,11525.65,11947.10,11153.68,11921.03,8541.49,6809.84,132939.20
4,광주,17596.51,23520.90,31532.22,29135.16,30909.39,32029.03,23177.62,31310.26,26379.55,29996.53,20637.14,11072.52,307296.83
5,대전,3513.09,3940.12,5626.49,5323.66,5956.38,6017.75,4430.20,5148.17,4496.11,5009.09,3590.26,2736.82,55788.14
6,울산,7486.88,7163.67,10157.68,10618.00,10621.83,11541.20,10128.00,10403.66,8384.50,11077.42,9514.81,7880.90,114978.55
7,세종,4724.81,5795.22,8065.31,7332.54,8818.34,8632.85,6392.34,7375.60,6362.25,6977.60,5175.17,3398.66,79050.69
8,경기,96125.05,122294.10,163063.01,153173.97,185172.38,173452.59,144538.02,153068.94,138017.89,145965.18,109399.60,80590.80,1664861.53
9,충북,92987.71,109695.12,152983.22,145665.61,166521.27,166349.36,128502.06,143679.02,126525.01,134651.20,104741.11,70397.62,1542698.31
10,충남,221947.58,269002.74,361349.78,328672.46,366971.81,367768.35,280378.27,336207.09,284707.06,319150.59,219583.79,129863.58,3485603.10
11,전남,405338.23,495889.88,650520.70,589473.59,607752.62,618359.26,455614.82,662593.07,547720.30,626395.17,434782.90,288347.21,6382787.75
12,경북,249889.99,260803.10,357925.31,360262.22,381720.54,394881.28,312968.10,337131.17,295258.68,345076.94,277837.92,229384.91,3803140.16
13,경남,137044.81,141396.48,183099.50,182988.76,181122.20,191906.09,143608.11,178204.55,149106.28,181723.12,147677.23,122097.11,1939974.24
14,제주,36945.81,46890.20,64839.46,65217.46,60312.35,58834.26,47042.76,67168.06,59303.45,68017.06,45306.34,28634.90,648512.11
15,강원,102653.16,148092.61,204305.78,191988.90,226017.19,215012.93,179363.29,176589.42,164846.45,175622.37,138887.55,96956.61,2020336.26
16,전북,357180.14,405649.52,549019.63,492354.60,533021.04,546738.66,414973.43,514665.65,430489.22,492891.38,341233.59,200732.06,5278948.92

In [22]:
final23 = pd.pivot_table(local23, index="구분", values="총합")
final23

            총합
구분
강원  2020336.26
경기  1664861.53
경남  1939974.24
경북  3803140.16
광주   307296.83
대구   352471.65
대전    55788.14
부산   239889.96
서울    56293.02
세종    79050.69
울산   114978.55
인천   132939.20
전남  6382787.75
전북  5278948.92
제주   648512.11
충남  3485603.10
충북  1542698.31

In [27]:
years = [2019, 2020, 2021, 2022, 2023]
final = pd.concat([final19, final20, final21, final22, final23], axis=1)
final.columns = years
final = final.transpose()
final = final.reset_index()

In [29]:
final.to_csv(DATA_PATH + "지역별 태양광 발전량 (19-23).csv")