In [2]:
import pandas as pd

x = pd.read_csv('data2/산업분류별 월별 전력사용량_20241011.csv')
x

,산업분류별 월별 전력사용량 ( 20241011 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 전체(시도), 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2024년 07 월 ~ 2024년 07월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,202407,전체(시도),전체(시 / 군 / 구),가구내고용활동및달리분류되지않은자가소비생산활동,434,"296,694","68,545,489",231.0
4,202407,전체(시도),전체(시 / 군 / 구),건설업,"85,258","342,547,098","68,849,096,845",201.0
...,...,...,...,...,...,...,...,...
390,202407,충청북도,전체,"전문,과학및기술서비스업","1,443","15,783,394","2,889,982,578",183.1
391,202407,충청북도,전체,정보통신업,"10,865","19,849,575","3,323,228,696",167.4
392,202407,충청북도,전체,제조업,"14,050","1,373,465,527","244,752,976,204",178.2
393,202407,충청북도,전체,"협회및단체,수리및기타개인서비스업","9,087","13,238,587","2,930,083,842",221.3
394,202407,충청북도,전체,합계,"315,976","1,951,695,444","345,282,613,041",176.9

In [31]:
data_2017_1_2017_6 = pd.read_csv('data2/산업분류별 월별 전력사용량_2017_1_2017_6.csv', header=3)
data_2017_7_2017_12 = pd.read_csv('data2/산업분류별 월별 전력사용량_2017_7_2017_12.csv', header=3)
data_2018_1_2019_6 = pd.read_csv('data2/산업분류별 월별 전력사용량_2018_1_2018_6.csv', header=3)
data_2018_7_2019_12 = pd.read_csv('data2/산업분류별 월별 전력사용량_2018_7_2018_12.csv', encoding='cp949', header=3)
data_2019_1_2019_6 = pd.read_csv('data2/산업분류별 월별 전력사용량_2019_1_2019_6.csv', encoding='cp949', header=3)
data_2019_7_2019_12 = pd.read_csv('data2/산업분류별 월별 전력사용량_2019_7_2019_12.csv', encoding='cp949', header=3)
data_2020_1_2020_6 = pd.read_csv('data2/산업분류별 월별 전력사용량_2020_1_2020_6.csv', header=3)
data_2020_7_2020_12 = pd.read_csv('data2/산업분류별 월별 전력사용량_2020_7_2020_12.csv', header=3)
data_2021_1_2021_6 = pd.read_csv('data2/산업분류별 월별 전력사용량_2021_1_2021_6.csv', header=3)
data_2021_7_2021_12 = pd.read_csv('data2/산업분류별 월별 전력사용량_2021_07_2021_12.csv', header=3)
data_2022_1_2022_6 = pd.read_csv('data2/산업분류별 월별 전력사용량_2022_01_2022_06.csv', header=3)
data_2022_7_2022_12 = pd.read_csv('data2/산업분류별 월별 전력사용량_2022_07_2022_12.csv', header=3)

In [32]:
data_2017_1_2017_6

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
0,201701,전체(시도),전체(시 / 군 / 구),"가구내고용,미분류자가소비생산",528,"571,710","86,427,025",151.2
1,201701,전체(시도),전체(시 / 군 / 구),건설업,"70,529","367,547,850","49,248,531,866",134.0
2,201701,전체(시도),전체(시 / 군 / 구),"공공행정, 국방 및 사회보장 행정","34,768","535,494,134","69,556,707,643",129.9
3,201701,전체(시도),전체(시 / 군 / 구),광업,"4,614","154,468,194","21,722,675,394",140.6
4,201701,전체(시도),전체(시 / 군 / 구),교육 서비스업,"69,866","891,054,335","90,642,321,916",101.7
...,...,...,...,...,...,...,...,...
2344,201706,충청북도,전체,제조업,"9,933","969,065,181","114,874,251,953",118.5
2345,201706,충청북도,전체,"출판영상,방송통신정보서비스업","7,972","15,571,824","1,734,607,210",111.4
2346,201706,충청북도,전체,하수폐기처리원료재생환경복원,"1,788","19,391,566","2,270,141,437",117.1
2347,201706,충청북도,전체,"협회단체,수리기타개인서비스업","9,215","12,441,193","1,940,414,465",156
2348,201706,충청북도,전체,합계,"248,936","1,350,098,172","159,593,307,437",118.2

In [33]:
data_2019_1_2019_6

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
0,201901,전체(시도),전체(시 / 군 / 구),가구내고용활동및달리분류되지않은자가소비생산활동,484,"530,866","78,262,080",147.4
1,201901,전체(시도),전체(시 / 군 / 구),건설업,"75,778","390,486,507","51,913,457,724",132.9
2,201901,전체(시도),전체(시 / 군 / 구),"공공 행정, 국방 및 사회보장 행정","39,053","602,519,463","77,474,124,284",128.6
3,201901,전체(시도),전체(시 / 군 / 구),광업,"3,633","133,185,444","18,422,367,975",138.3
4,201901,전체(시도),전체(시 / 군 / 구),교육 서비스업,"69,826","1,043,248,273","106,248,045,013",101.8
...,...,...,...,...,...,...,...,...
2362,201906,충청북도,전체,"협회 및 단체, 수리 및 기타 개인 서비스업","9,068","12,556,458","1,971,093,854",157
2363,201906,충청북도,전체,합계,"274,187","1,854,621,325","212,455,430,830",114.6
2364,201906,황해북도,전체,부동산업,9,"87,695","22,322,102",254.5
2365,201906,황해북도,전체,"수도, 하수 및 폐기물 처리, 원료 재생업",5호미만제거,-,-,-
2366,201906,황해북도,전체,합계,9,"87,695","22,322,102",254.5

In [36]:
data_2022_1_2022_6

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
0,202201,전체(시도),전체(시 / 군 / 구),"가구내고용,미분류자가소비생산",420,"437,002","67,479,235",154.4
1,202201,전체(시도),전체(시 / 군 / 구),건설업,"85,971","463,385,009","61,401,994,546",132.5
2,202201,전체(시도),전체(시 / 군 / 구),"공공행정, 국방 및 사회보장 행정","47,988","655,571,192","85,092,930,721",129.8
3,202201,전체(시도),전체(시 / 군 / 구),광업,"3,789","160,092,926","21,624,889,576",135.1
4,202201,전체(시도),전체(시 / 군 / 구),교육 서비스업,"72,253","1,097,093,451","110,633,414,274",100.8
...,...,...,...,...,...,...,...,...
2355,202206,충청북도,전체,제조업,"13,312","1,564,234,299","190,283,667,376",121.6
2356,202206,충청북도,전체,"출판영상,방송통신정보서비스업","10,263","19,725,396","2,210,756,148",112.1
2357,202206,충청북도,전체,하수폐기처리원료재생환경복원,"1,997","25,569,425","3,170,365,737",124
2358,202206,충청북도,전체,"협회단체,수리기타개인서비스업","9,066","12,119,153","2,033,778,453",167.8
2359,202206,충청북도,전체,합계,"299,716","2,065,020,343","252,886,934,862",122.5

In [35]:
data_2020_7_2020_12

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
0,202007,전체(시도),전체(시 / 군 / 구),가구내고용활동및달리분류되지않은자가소비생산활동,450,"376,237","67,128,907",178.4
1,202007,전체(시도),전체(시 / 군 / 구),건설업,"79,443","277,873,988","44,118,796,844",158.8
2,202007,전체(시도),전체(시 / 군 / 구),"공공 행정, 국방 및 사회보장 행정","43,948","481,442,350","71,786,372,770",149.1
3,202007,전체(시도),전체(시 / 군 / 구),광업,"3,556","123,605,876","18,437,448,833",149.2
4,202007,전체(시도),전체(시 / 군 / 구),교육 서비스업,"69,221","658,662,826","79,353,936,383",120.5
...,...,...,...,...,...,...,...,...
2362,202012,충청북도,전체,"협회 및 단체, 수리 및 기타 개인 서비스업","9,073","18,024,993","2,622,260,568",145.5
2363,202012,충청북도,전체,합계,"286,311","2,061,798,183","237,303,265,796",115.1
2364,202012,황해북도,전체,부동산업,9,0,0,0
2365,202012,황해북도,전체,"수도, 하수 및 폐기물 처리, 원료 재생업",5호미만제거,-,-,-
2366,202012,황해북도,전체,합계,9,0,0,�

In [43]:
data = pd.concat([data_2017_1_2017_6, data_2017_7_2017_12, data_2018_1_2019_6, data_2018_7_2019_12, data_2019_1_2019_6, data_2019_7_2019_12, data_2020_1_2020_6, data_2020_7_2020_12, data_2021_1_2021_6, data_2021_7_2021_12, data_2022_1_2022_6, data_2022_7_2022_12])
data

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
0,201701,전체(시도),전체(시 / 군 / 구),"가구내고용,미분류자가소비생산",528,"571,710","86,427,025",151.2
1,201701,전체(시도),전체(시 / 군 / 구),건설업,"70,529","367,547,850","49,248,531,866",134.0
2,201701,전체(시도),전체(시 / 군 / 구),"공공행정, 국방 및 사회보장 행정","34,768","535,494,134","69,556,707,643",129.9
3,201701,전체(시도),전체(시 / 군 / 구),광업,"4,614","154,468,194","21,722,675,394",140.6
4,201701,전체(시도),전체(시 / 군 / 구),교육 서비스업,"69,866","891,054,335","90,642,321,916",101.7
...,...,...,...,...,...,...,...,...
2340,202212,충청북도,전체,제조업,"13,495","1,624,994,320","230,367,018,601",141.8
2341,202212,충청북도,전체,"출판영상,방송통신정보서비스업","10,528","18,489,918","2,568,906,764",138.9
2342,202212,충청북도,전체,하수폐기처리원료재생환경복원,"2,014","27,704,884","4,139,395,606",149.4
2343,202212,충청북도,전체,"협회단체,수리기타개인서비스업","9,077","19,703,984","3,224,255,842",163.6
2344,202212,충청북도,전체,합계,"305,476","2,220,188,169","314,635,554,692",141.7

In [42]:
data.to_csv('data2/산업분류별 월별 전력사용량_2017_2022.csv', index = False)
x = pd.read_csv('data2/산업분류별 월별 전력사용량_2017_2022.csv')
x

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
0,201701,전체(시도),전체(시 / 군 / 구),"가구내고용,미분류자가소비생산",528,"571,710","86,427,025",151.2
1,201701,전체(시도),전체(시 / 군 / 구),건설업,"70,529","367,547,850","49,248,531,866",134.0
2,201701,전체(시도),전체(시 / 군 / 구),"공공행정, 국방 및 사회보장 행정","34,768","535,494,134","69,556,707,643",129.9
3,201701,전체(시도),전체(시 / 군 / 구),광업,"4,614","154,468,194","21,722,675,394",140.6
4,201701,전체(시도),전체(시 / 군 / 구),교육 서비스업,"69,866","891,054,335","90,642,321,916",101.7
...,...,...,...,...,...,...,...,...
28303,202212,충청북도,전체,제조업,"13,495","1,624,994,320","230,367,018,601",141.8
28304,202212,충청북도,전체,"출판영상,방송통신정보서비스업","10,528","18,489,918","2,568,906,764",138.9
28305,202212,충청북도,전체,하수폐기처리원료재생환경복원,"2,014","27,704,884","4,139,395,606",149.4
28306,202212,충청북도,전체,"협회단체,수리기타개인서비스업","9,077","19,703,984","3,224,255,842",163.6
28307,202212,충청북도,전체,합계,"305,476","2,220,188,169","314,635,554,692",141.7

In [40]:
data.groupby('시구').count()

           년월   시군구  계약구분  고객호수(호)  사용량(kWh)  전기요금(원)  평균판매단가(원/kWh)
시구
강원도      1584  1584  1584     1584      1584     1584           1584
경기도      1587  1587  1587     1587      1587     1587           1587
경상남도     1584  1584  1584     1584      1584     1584           1584
경상북도     1584  1584  1584     1584      1584     1584           1584
광주광역시    1584  1584  1584     1584      1584     1584           1584
대구광역시    1584  1584  1584     1584      1584     1584           1584
대전광역시    1562  1562  1562     1562      1562     1562           1562
미분류        10    10    10       10        10       10             10
부산광역시    1584  1584  1584     1584      1584     1584           1584
서울특별시    1584  1584  1584     1584      1584     1584           1584
세종특별자치시  1512  1512  1512     1512      1512     1512           1512
시구         12    12    12       12        12       12             12
울산광역시    1512  1512  1512     1512      1512     1512           1512
인천광역시    1584  1584  1584     1584      1584     1584           1584
전라남도     1512  1512  1512     1512      1512     1512           1512
전라북도     1584  1584  1584     1584      1584     1584           1584
전체(시도)   1515  1515  1515     1515      1515     1515           1515
제주특별자치도  1584  1584  1584     1584      1584     1584           1584
충청남도     1584  1584  1584     1584      1584     1584           1584
충청북도     1512  1512  1512     1512      1512     1512           1512
합계         12    12    12       12        12       12             12
황해북도      126   126   126      126       126      126            126