In [2]:
import pandas as pd
DATA_PATH = "data/"
df2 = pd.read_csv("data/발전전력량_추이.csv")
df2

,월별(1),2017,2017.1,2017.2,2017.3,2017.4,2017.5,2017.6,2017.7,2017.8,...,2022.36,2022.37,2022.38,2022.39,2022.40,2022.41,2022.42,2022.43,2022.44,2022.45
0,월별(1),한전 및 자회사,한전 및 자회사,한전 및 자회사,한전 및 자회사,한전 및 자회사,한전 및 자회사,한전 및 자회사,한전 및 자회사,한전 및 자회사,...,사업자(종합),사업자(종합),사업자(종합),사업자(종합),사업자(종합),상용자가,상용자가,상용자가,총발전량,총발전량
1,월별(1),소계,수력,수력,수력,수력,기력,기력,기력,기력,...,원자력,신재생,집단,내연력,기타,소계,한전구입,자가소비,사업자+한전구입,사업자+상용자가
2,월별(1),소계,소계,일반,양수,소수력,소계,무연탄,유연탄,중유,...,소계,소계,소계,소계,소계,소계,소계,소계,소계,소계
3,합계,426484068,5262507,917300,4186353,158855,232631450,4426611,222759888,5224768,...,176054012,47266256,49158704,570046,1171543,28635808,451043,28184765,594400365,622585130
4,1월,38858632,417953,37613,365932,14408,21465583,636666,19795166,939839,...,16103260,3470434,5585160,54726,87518,...,43696,...,54792301,...
5,2월,35496007,402267,37701,352201,12366,19168753,590463,17626862,867864,...,13989890,3745027,5045196,58129,84515,...,72864,...,48487502,...
6,3월,35672236,389424,49148,328292,11984,19181112,465244,18499247,173914,...,13866525,3880039,5324102,60216,97061,...,25090,...,49659153,...
7,4월,33240589,378089,50537,314478,13074,17105922,462381,16452195,191346,...,13385162,4268206,3916566,53290,97776,...,24337,...,44858870,...
8,5월,33996468,457306,78128,367704,11474,17575225,405831,17024443,144951,...,14609832,4893738,2885380,40090,98190,...,14217,...,46180830,...
9,6월,32474815,437561,67851,360569,9140,16885157,256351,16334113,294694,...,14725941,3829447,3426932,41707,98344,...,13735,...,47586861,...
10,7월,38434374,482430,156030,311432,14969,21240268,274802,20409147,556319,...,15354809,4021608,3853755,63090,108010,...,16742,...,55027406,...
11,8월,38235049,667020,217315,435068,14637,21849877,369087,21147470,333320,...,16308978,3961663,3621352,47316,101643,...,55743,...,53963962,...
12,9월,35201531,504595,70093,419742,14761,19915119,215171,19462697,237250,...,14093577,3971828,2873874,31613,96034,...,37494,...,46308310,...
13,10월,33344138,428783,50664,362831,15287,18495155,280495,18054688,159972,...,14381733,4188030,3338275,39605,103911,...,99070,...,45741659,...
14,11월,33797360,342942,50198,279294,13451,18285230,221807,17742441,320982,...,14005635,3504268,3940448,35487,98801,...,24701,...,46223019,...
15,12월,37732868,354137,52023,288810,13304,21464050,248312,20211420,1004318,...,15228671,3531968,5347664,44778,99739,...,23354,...,55570492,...

In [3]:
filtered_columns = df2.columns[df2.iloc[0].str.contains('총발전량', na=False)]


filtered_df = df2[filtered_columns]
print(filtered_df)

      2017.39    2018.37    2019.39    2020.42    2021.44    2021.45  \
0        총발전량       총발전량       총발전량       총발전량       총발전량       총발전량
1    사업자+한전구입   사업자+한전구입   사업자+한전구입   사업자+한전구입   사업자+한전구입   사업자+상용자가
2          소계         소계         소계         소계         소계         소계
3   553530107  570646507  563040305  552162160  576809488  607767903
4    49542649   53394215   52903789   49851376   53155603        ...
5    45498559   46472301   44932402   46448998   44973731        ...
6    47049584   47248780   47209275   46164928   47192720        ...
7    42021612   43155441   43945853   42255395   43637495        ...
8    42820063   44297930   44334192   41581363   44304640        ...
9    43430386   44494153   43793268   43829618   45788106        ...
10   49651095   52020038   49739732   46683450   54144925        ...
11   48951121   53234984   51641721   51050911   51795796        ...
12   44195917   43527290   44462306   44599442   45410303        ...
13   42386526   44927441   44629604   43164475   46147145        ...
14   46080764   46036823   45164724   44932096   46885417        ...
15   51901834   51837111   50283440   51600108   53373609        ...

      2022.44    2022.45
0        총발전량       총발전량
1    사업자+한전구입   사업자+상용자가
2          소계         소계
3   594400365  622585130
4    54792301        ...
5    48487502        ...
6    49659153        ...
7    44858870        ...
8    46180830        ...
9    47586861        ...
10   55027406        ...
11   53963962        ...
12   46308310        ...
13   45741659        ...
14   46223019        ...
15   55570492        ...

In [8]:
# 열 삭제
filtered_df2 = filtered_df.drop(columns=[filtered_df.columns[5], filtered_df.columns[7]])
print(filtered_df2)

      2017.39    2018.37    2019.39    2020.42    2021.44    2022.44
0        총발전량       총발전량       총발전량       총발전량       총발전량       총발전량
1    사업자+한전구입   사업자+한전구입   사업자+한전구입   사업자+한전구입   사업자+한전구입   사업자+한전구입
2          소계         소계         소계         소계         소계         소계
3   553530107  570646507  563040305  552162160  576809488  594400365
4    49542649   53394215   52903789   49851376   53155603   54792301
5    45498559   46472301   44932402   46448998   44973731   48487502
6    47049584   47248780   47209275   46164928   47192720   49659153
7    42021612   43155441   43945853   42255395   43637495   44858870
8    42820063   44297930   44334192   41581363   44304640   46180830
9    43430386   44494153   43793268   43829618   45788106   47586861
10   49651095   52020038   49739732   46683450   54144925   55027406
11   48951121   53234984   51641721   51050911   51795796   53963962
12   44195917   43527290   44462306   44599442   45410303   46308310
13   42386526   44927441   44629604   43164475   46147145   45741659
14   46080764   46036823   45164724   44932096   46885417   46223019
15   51901834   51837111   50283440   51600108   53373609   55570492

In [9]:
# 행삭제
filtered_df2 = filtered_df2.drop([0, 1, 2])
filtered_df2.reset_index(drop=True, inplace=True)
print(filtered_df2)

      2017.39    2018.37    2019.39    2020.42    2021.44    2022.44
0   553530107  570646507  563040305  552162160  576809488  594400365
1    49542649   53394215   52903789   49851376   53155603   54792301
2    45498559   46472301   44932402   46448998   44973731   48487502
3    47049584   47248780   47209275   46164928   47192720   49659153
4    42021612   43155441   43945853   42255395   43637495   44858870
5    42820063   44297930   44334192   41581363   44304640   46180830
6    43430386   44494153   43793268   43829618   45788106   47586861
7    49651095   52020038   49739732   46683450   54144925   55027406
8    48951121   53234984   51641721   51050911   51795796   53963962
9    44195917   43527290   44462306   44599442   45410303   46308310
10   42386526   44927441   44629604   43164475   46147145   45741659
11   46080764   46036823   45164724   44932096   46885417   46223019
12   51901834   51837111   50283440   51600108   53373609   55570492

In [10]:
filtered_df2.columns=['2017','2018','2019','2020','2021','2022']
print(filtered_df2)

         2017       2018       2019       2020       2021       2022
0   553530107  570646507  563040305  552162160  576809488  594400365
1    49542649   53394215   52903789   49851376   53155603   54792301
2    45498559   46472301   44932402   46448998   44973731   48487502
3    47049584   47248780   47209275   46164928   47192720   49659153
4    42021612   43155441   43945853   42255395   43637495   44858870
5    42820063   44297930   44334192   41581363   44304640   46180830
6    43430386   44494153   43793268   43829618   45788106   47586861
7    49651095   52020038   49739732   46683450   54144925   55027406
8    48951121   53234984   51641721   51050911   51795796   53963962
9    44195917   43527290   44462306   44599442   45410303   46308310
10   42386526   44927441   44629604   43164475   46147145   45741659
11   46080764   46036823   45164724   44932096   46885417   46223019
12   51901834   51837111   50283440   51600108   53373609   55570492

In [12]:
filtered_df2.to_csv('발전량_민전총량.csv', header=True)