In [1]:
import pandas as pd
DATA_PATH = "data/"
df2 = pd.read_csv("data/발전전력량_추이.csv")
df2

,월별(1),2017,2017.1,2017.2,2017.3,2017.4,2017.5,2017.6,2017.7,2017.8,...,2022.36,2022.37,2022.38,2022.39,2022.40,2022.41,2022.42,2022.43,2022.44,2022.45
0,월별(1),한전 및 자회사,한전 및 자회사,한전 및 자회사,한전 및 자회사,한전 및 자회사,한전 및 자회사,한전 및 자회사,한전 및 자회사,한전 및 자회사,...,사업자(종합),사업자(종합),사업자(종합),사업자(종합),사업자(종합),상용자가,상용자가,상용자가,총발전량,총발전량
1,월별(1),소계,수력,수력,수력,수력,기력,기력,기력,기력,...,원자력,신재생,집단,내연력,기타,소계,한전구입,자가소비,사업자+한전구입,사업자+상용자가
2,월별(1),소계,소계,일반,양수,소수력,소계,무연탄,유연탄,중유,...,소계,소계,소계,소계,소계,소계,소계,소계,소계,소계
3,합계,426484068,5262507,917300,4186353,158855,232631450,4426611,222759888,5224768,...,176054012,47266256,49158704,570046,1171543,28635808,451043,28184765,594400365,622585130
4,1월,38858632,417953,37613,365932,14408,21465583,636666,19795166,939839,...,16103260,3470434,5585160,54726,87518,...,43696,...,54792301,...
5,2월,35496007,402267,37701,352201,12366,19168753,590463,17626862,867864,...,13989890,3745027,5045196,58129,84515,...,72864,...,48487502,...
6,3월,35672236,389424,49148,328292,11984,19181112,465244,18499247,173914,...,13866525,3880039,5324102,60216,97061,...,25090,...,49659153,...
7,4월,33240589,378089,50537,314478,13074,17105922,462381,16452195,191346,...,13385162,4268206,3916566,53290,97776,...,24337,...,44858870,...
8,5월,33996468,457306,78128,367704,11474,17575225,405831,17024443,144951,...,14609832,4893738,2885380,40090,98190,...,14217,...,46180830,...
9,6월,32474815,437561,67851,360569,9140,16885157,256351,16334113,294694,...,14725941,3829447,3426932,41707,98344,...,13735,...,47586861,...
10,7월,38434374,482430,156030,311432,14969,21240268,274802,20409147,556319,...,15354809,4021608,3853755,63090,108010,...,16742,...,55027406,...
11,8월,38235049,667020,217315,435068,14637,21849877,369087,21147470,333320,...,16308978,3961663,3621352,47316,101643,...,55743,...,53963962,...
12,9월,35201531,504595,70093,419742,14761,19915119,215171,19462697,237250,...,14093577,3971828,2873874,31613,96034,...,37494,...,46308310,...
13,10월,33344138,428783,50664,362831,15287,18495155,280495,18054688,159972,...,14381733,4188030,3338275,39605,103911,...,99070,...,45741659,...
14,11월,33797360,342942,50198,279294,13451,18285230,221807,17742441,320982,...,14005635,3504268,3940448,35487,98801,...,24701,...,46223019,...
15,12월,37732868,354137,52023,288810,13304,21464050,248312,20211420,1004318,...,15228671,3531968,5347664,44778,99739,...,23354,...,55570492,...

In [2]:
filtered_columns = df2.columns[df2.iloc[0].str.contains('상용자가', na=False)]

filtered_df = df2[filtered_columns]
print(filtered_df)

   2017.38 2018.36  2019.38  2020.41   2021.41  2021.42   2021.43   2022.41  \
0     상용자가    상용자가     상용자가     상용자가      상용자가     상용자가      상용자가      상용자가
1     한전구입    한전구입     한전구입     한전구입        소계     한전구입      자가소비        소계
2       소계      소계       소계       소계        소계       소계        소계        소계
3   304506  798850  1146405  1676440  31982353  1023939  30958414  28635808
4    41160  103006   123238   163078       ...   187466       ...       ...
5    46173   88962    98119   186185       ...   144614       ...       ...
6    37487   62176    94519   161733       ...   152651       ...       ...
7    11829   44228    68055   138726       ...    92326       ...       ...
8     5436   46683    39321   130525       ...    18465       ...       ...
9     5520   60898    53770   209093       ...    69735       ...       ...
10    7751   38407    34368   149795       ...    98352       ...       ...
11    5855   29282    37795   147518       ...    94986       ...       ...
12   13050   50561   123962    90953       ...    23229       ...       ...
13   18967   60363   131402   127491       ...    35129       ...       ...
14   60114   97675   177891    49273       ...    56125       ...       ...
15   51164  116610   163966   122070       ...    50862       ...       ...

   2022.42   2022.43
0     상용자가      상용자가
1     한전구입      자가소비
2       소계        소계
3   451043  28184765
4    43696       ...
5    72864       ...
6    25090       ...
7    24337       ...
8    14217       ...
9    13735       ...
10   16742       ...
11   55743       ...
12   37494       ...
13   99070       ...
14   24701       ...
15   23354       ...

In [3]:
# 열 삭제
filtered_df2 = filtered_df.drop(columns=[filtered_df.columns[4], filtered_df.columns[6],filtered_df.columns[7],filtered_df.columns[9]])
print(filtered_df2)

   2017.38 2018.36  2019.38  2020.41  2021.42 2022.42
0     상용자가    상용자가     상용자가     상용자가     상용자가    상용자가
1     한전구입    한전구입     한전구입     한전구입     한전구입    한전구입
2       소계      소계       소계       소계       소계      소계
3   304506  798850  1146405  1676440  1023939  451043
4    41160  103006   123238   163078   187466   43696
5    46173   88962    98119   186185   144614   72864
6    37487   62176    94519   161733   152651   25090
7    11829   44228    68055   138726    92326   24337
8     5436   46683    39321   130525    18465   14217
9     5520   60898    53770   209093    69735   13735
10    7751   38407    34368   149795    98352   16742
11    5855   29282    37795   147518    94986   55743
12   13050   50561   123962    90953    23229   37494
13   18967   60363   131402   127491    35129   99070
14   60114   97675   177891    49273    56125   24701
15   51164  116610   163966   122070    50862   23354

In [4]:
# 행삭제
filtered_df2 = filtered_df2.drop([0, 1, 2])
filtered_df2.reset_index(drop=True, inplace=True)
print(filtered_df2)

   2017.38 2018.36  2019.38  2020.41  2021.42 2022.42
0   304506  798850  1146405  1676440  1023939  451043
1    41160  103006   123238   163078   187466   43696
2    46173   88962    98119   186185   144614   72864
3    37487   62176    94519   161733   152651   25090
4    11829   44228    68055   138726    92326   24337
5     5436   46683    39321   130525    18465   14217
6     5520   60898    53770   209093    69735   13735
7     7751   38407    34368   149795    98352   16742
8     5855   29282    37795   147518    94986   55743
9    13050   50561   123962    90953    23229   37494
10   18967   60363   131402   127491    35129   99070
11   60114   97675   177891    49273    56125   24701
12   51164  116610   163966   122070    50862   23354

In [5]:
filtered_df2.columns=['2017','2018','2019','2020','2021','2022']
print(filtered_df2)

      2017    2018     2019     2020     2021    2022
0   304506  798850  1146405  1676440  1023939  451043
1    41160  103006   123238   163078   187466   43696
2    46173   88962    98119   186185   144614   72864
3    37487   62176    94519   161733   152651   25090
4    11829   44228    68055   138726    92326   24337
5     5436   46683    39321   130525    18465   14217
6     5520   60898    53770   209093    69735   13735
7     7751   38407    34368   149795    98352   16742
8     5855   29282    37795   147518    94986   55743
9    13050   50561   123962    90953    23229   37494
10   18967   60363   131402   127491    35129   99070
11   60114   97675   177891    49273    56125   24701
12   51164  116610   163966   122070    50862   23354

In [6]:
filtered_df2.to_csv('한전외발전총량.csv', header=True)